amilajack/eslint-plugin-compat

src/providers/CanIUseProvider.js
May happen if browserslist returns a browser version that is newer than what's in the caniuse-db.
This is probably not the best solution -- maybe it should parse and decrement the version number until it finds something that is in the database, but it at least avoids a crash.
=> Avoid crash when targetStats[version] is undefined

README.md
ESLint now supports more readable aliases:
https://eslint.org/docs/user-guide/configuring#configuring-rules
=> Clarify configuration

.babelrc, package.json, yarn.lock
Fixes #96.
The rule [`compat.js`](https://github.com/amilajack/eslint-plugin-compat/blob/b4c1f13b8a2a1ebc949918ef9e40229d3396dd3a/src/rules/compat.js) contains a ES2015 `export default`. Babel@6 compiles this to `exports.default =` ([source](https://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/)).
`default` is not an expected export key for `requireindex` in [`index.js`](https://github.com/amilajack/eslint-plugin-compat/blob/b4c1f13b8a2a1ebc949918ef9e40229d3396dd3a/src/index.js)
Adding [`babel-plugin-add-module-exports`](https://github.com/59naga/babel-plugin-add-module-exports) fixes the problem.
I've run the `yarn test` before the commit and after it.
Though some tests fail in the original repository, this fix didn't crush any other tests.
=> Fix 'export default' for Babel. Fixes #96

README.md, src/providers/KangaxProvider.js
(This is a suggestion PR.)
Because it is miss-leading that Kangax table implementation is
already supported 😇 
resolve https://github.com/amilajack/eslint-plugin-compat/issues/77
please review 🙏
=> Remove checklists for implementation from README

.gitignore, src/providers/CanIUseProvider.js
nits refactor.
Adding `isValid()` and `getUnsupportedTargets()` every time when adding a new rule to CanIUseProvider seems redundant, so fixed it.
Add `.vscode` to .gitignore as well (this is a nits change, so I mixed this commit)
please review 🙏
=> Inject isValid and getUnsupportedTargets in CanIUseProvider nodes isvalid

CHANGELOG.md, README.md, package.json, src/Lint.js, src/LintTypes.js, src/Versioning.js, src/providers/CanIUseProvider.js, src/providers/MdnProvider.js, src/providers/index.js, src/rules/compat.js, test/e2e.spec.js, yarn.lock
[ast-metadata-inferer](https://github.com/amilajack/ast-metadata-inferer) is a complementary project of mine that does the following things:
* AST node type of the API (`MemberExpression`, `NewExpression`, or `CallExpression`)
* Determines if an API is statically invoked (ex. `document.querySelector()`)
* Determines if an API is a CSS or JS API
* Provides compatibility information from `mdn-browser-compat-data`
* Adds support for ~4000 APIs 🎉 🎉 🎉 
* Likely performance regressions because of the number of accesses to the significant increased number of compat records
- Closes https://github.com/amilajack/eslint-plugin-compat/issues/104
- Closes https://github.com/amilajack/eslint-plugin-compat/issues/89
=> use ast-metadata-inferer

README.md, src/Lint.js, src/LintTypes.js, src/providers/CanIUseProvider.js
Handle cases where entire API is polyfiled. Here's an example of the kind of cases this PR covers:
```jsonc
{
// ...
"settings": {
"polyfills": [
// Example of marking entire API and all methods and properties as polyfilled
"Promise"
]
}
}
```
This will mark all the following APIs as polyfilled: `Promise.all`, `Promise.race`, `Promise.prototype.then`, etc
=> handle entire API polyfill case

README.md, src/Versioning.js, src/rules/compat.js, test/Versioning.spec.js, test/__snapshots__/Versioning.spec.js.snap
I've totally messed up my repository, therefore i started a repository and pull request. This makes #121 obsolete
This adds the possibility to specify browserlist as rule configuration in eslint e.g.
```js
{
// ...
"rules": [
"compat/compat": ["error", "defaults, not ie < 9"],
]
}
```
=> Add browserlist config as eslint rule config

README.md, package.json, src/rules/compat.js, test/e2e.spec.js
This PR recognizes locally defined polyfills by users and doesn't throw errors in those cases.
This is an error (when targeting IE):
```js
const a = new Set();
```
This PR allows the above to not be an error:
```js
class Set {} // A user defined polyfill
const a = new Set();
```
This PR does **not** handle the following cases, which will be addressed in later PR's:
```js
const n = navigator; // navigator is supported
n.serviceWorker // navigator.serviceWorker is supported and should throw
```
Fixes https://github.com/amilajack/eslint-plugin-compat/issues/192
Closes https://github.com/amilajack/eslint-plugin-compat/issues/195
=> support detecting locally defined polyfills

CHANGELOG.md, src/Lint.js, src/LintTypes.js, src/Versioning.js, src/providers/CanIUseProvider.js, src/providers/MdnProvider.js, src/providers/index.js, src/rules/compat.js, test/e2e.spec.js
This PR allows users to define custom compatibility records. This is useful for adding compatibility checks for APIs that are not supported by this plugin.
Docs: https://github.com/amilajack/eslint-plugin-compat/wiki/Custom-Compatibility-Records
Code:
```js
foo.bar();
```
Eslint Config
```jsonc
// .eslintrc.json
{
settings: {
browsers: ['ie 10'],
records: [
{
name: 'foo.bar',
id: 'foo.bar',
astNodeType: 'MemberExpression',
protoChain: ['foo', 'bar'],
protoChainId: 'foo.bar',
object: 'foo',
property: 'bar',
recordMatchesNode() {
return false;
},
getUnsupportedTargets() {
return ['IE 10'];
}
}
]
},
}
```
Closes https://github.com/amilajack/eslint-plugin-compat/issues/90
=> allow custom user records

src/Versioning.js, src/rules/compat.js, test/CanIUseProvider.spec.js, test/Versioning.spec.js
Closes https://github.com/amilajack/eslint-plugin-compat/issues/42
This allows the plugin to run correctly despite being called from a cwd that is not the root of the project.
=> relative browsers config lookup

CHANGELOG.md, src/Lint.js, src/LintTypes.js, src/rules/compat.js
Re: https://github.com/amilajack/eslint-plugin-compat/issues/193
@amilajack I took a look at the performance here, and found that a surprising amount of the cost of the `lint()` function is coming from those `polyfills.has()` lookups, even when `polyfills` is a very small set (the project I tested this change against has only 3). So the main optimization here is:
* `filter` rules down to those that aren't polyfilled
* Run remaining rules through `rule.isValid()`
* Make a single pass through the rules instead of using a separate `filter` step
* Check `rule.isValid()` before checking for polyfills
This simple change cut the time it takes to run `compat/compat` against my project by more than half, from ~13s to ~5.5s! 😮
=> Optimize loop in lint()

.flowconfig, package.json, src/Lint.js, src/LintTypes.js, src/providers/CanIUseProvider.js, src/providers/MdnProvider.js, src/rules/compat.js, test/__snapshots__/Versioning.spec.js.snap, yarn.lock
Closes https://github.com/amilajack/eslint-plugin-compat/issues/193
Currently, the `Lint()` function loops through all 4361 rules on every node. The cost of all that looping really adds up! For most projects, most of those rules are irrelevant because they only fail for very old or esoteric browsers. In the project I used to test this branch, the browser list is
```
[
'last 3 chrome version',
'last 3 firefox version',
'last 2 edge version',
'last 2 safari version',
'IE 11'
]
```
and only 1679 of the rules potentially fail. For a project that only supports modern browsers (no IE11), the relevant set of rules would be much smaller.
This PR filters the set of rules based on the targeted browser list, removing the need to iterate through irrelevant rules on every node. It does that filtering …
=> Pre-filter and sort rules for 400% perf boost

src/rules/compat.js
The rule schema is empty. This disallows using the second parameter in .eslintrc.json as browserconfig.
Because of that this rule errors with
```
Configuration for rule "compat/compat" is invalid: Value ["last 1 version, last 1 firefox version, last 1 edge version, ie 11, not safari < 12"] should NOT have more than 0 items.
```
when it should accept it as an option.
This causes an issue for our plugin that relies on your plugin: https://github.com/forcedotcom/eslint-plugin-aura/pull/4
=> Add schema to support browserlist as a second paramenter in eslintrc

src/providers/CanIUseProvider.js
Previously unknown browsers would cause failures with unhelpful messages, e.g.,
```
<feature> is not supported in undefined 2.5  compat/compat
```
I've added a mapping for KaiOS & a fallback to raw name when no mapping is available.
=> Added missing browser mapping and default fallback

src/providers/MdnProvider.js, test/MdnProvider.spec.js
=> fix: support safari TP as a target

src/rules/compat.js
Regarding removal of "fixable", per https://eslint.org/docs/developer-guide/working-with-rules#options-schemas :
> Omit the fixable property if the rule is not fixable.
Regarding `meta.type`, though generally more useful with the likes of [`eslint --fix-type`](https://eslint.org/docs/user-guide/command-line-interface#fix-type), besides for general documentation, I'm intending to release an eslint badge formatter which can count total number of violations by type (e.g., 5 problem, 10 suggestion, 4 layout violations).
=> Remove `fixable` and add `meta.type`

CHANGELOG.md, azure-pipelines.yml, src/Lint.js, src/rules/compat.js, test/e2e.spec.js
Previously, feature detection of APIs would report compatibility errors.  This PR fixes that. The following cases now do not error:
```js
if (fetch) {
fetch()
}
if (Array.prototype.flat) {
new Array.flat()
}
if (fetch && otherConditions) {
fetch()
}
if (window.fetch) {
fetch()
}
if ('fetch' in window) {
fetch()
}
```
Fixes https://github.com/amilajack/eslint-plugin-compat/issues/26
Fixes https://github.com/amilajack/eslint-plugin-compat/issues/203
Fixes #185
=> feat: allow feature detection of APIs

src/lint.ts
Fixes `TypeError: Cannot read property 'type' of undefined`.
As reported in https://github.com/amilajack/eslint-plugin-compat/issues/332#issuecomment-636502543 by @rj-david.
1. Checkout https://github.com/handlebars-lang/handlebars.js
2. Update `eslint-plugin-compat` to latest version (`3.8.0-0`)
3. Run `npm run lint`
=> Check for missing object in ESLintNode

test/__snapshots__/e2e-repo.spec.ts.snap, test/benchmarks.ts, test/e2e-repo.spec.ts
Move fatal error check from `benchmarks.ts` to `e2e-repo.spec.ts`
=> Move fatal error check

.github/workflows/semantic-pr.yml
Adds github workflow check for PR titles to have semantic/conventional title.
Follows the default conventions used by [`semantic-release`](https://github.com/semantic-release/semantic-release#commit-message-format)
=> ci: semantic-pr title check

.github/workflows/release.yml, package.json, release.config.js, tsconfig.json
Builds upon #418 so that eslint-plugin-compat can have an automated release workflow. From now on updates to the following are automated:
- semver bumps
- npm registry
- CHANEGLOG.md
- GitHub release
Users with collaborator access should be able to create releases from the [actions](https://github.com/amilajack/eslint-plugin-compat/actions) page
=> ci: automated semantic-release workflow

package.json, test/__snapshots__/helpers.spec.ts.snap, yarn.lock
As suggested in #354, this Pull Request bumps dependencies to update compatibility data.
Only "production" dependencies were updated (to the notable exception of `find-up` in order to preserve old node support).
I can take of devs ones and update PR if asked.
Tests snapshot were updated in a dedicated commit.
Fixes https://github.com/amilajack/eslint-plugin-compat/issues/354
=> chore(deps): updates in order to fix IE undetected compat infringements

.github/workflows/release.yml, .github/workflows/test.yml, azure-pipelines.yml, package.json, test/__snapshots__/helpers.spec.ts.snap, yarn.lock
Fixes https://github.com/amilajack/eslint-plugin-compat/issues/488
=> feat: eslint@8 support

src/rules/compat.ts
babel now allows `.cjs` config files to allow ESM->CommonJS compatibility.
In an ESM package this will allow having "old" CommonJS babel config files.
Fixes #498
=> feat: add new CommonJS babel config files

src/rules/compat.ts
In a large codebase, this gets extremely expensive and contributes to 25-30% of our total lint time (pushing it above 15 minutes).
I've lifted the memoized fn, as in the majority of cases the targetsJSON string is gonna be the same for the entire codebase, so this presents a significant savings.
=> fix: hoist memoized fn for getting rules

src/rules/compat.ts
This PR fixes issue #528 by adding a missing line to `src/rules/compat.ts`
=> fix: findUp is not defined

package-lock.json, package.json
closes https://github.com/amilajack/eslint-plugin-compat/issues/541
=> fix: drop core-js

package-lock.json, package.json, src/helpers.ts, src/types.ts, test/__snapshots__/helpers.spec.ts.snap, test/e2e.spec.ts
The protochain array was coming back as `[undefined, 'at']` for `"foo".at(1)` rather than coming back as `["String", "at"]` which makes it look up the correct compat data in the dataset.
I check for a string literal and return `["String"]` for it in member expressions so that the protochain key is created correctly.
I did the same fix for `ArrayExpression` so that the constructed protochain returns `"Array"` and I also added an e2e test and updated the compatibility databases.
Fixes: #395, https://github.com/amilajack/eslint-plugin-compat/issues/539, #445, https://github.com/amilajack/eslint-plugin-compat/issues/540
=> fix(helpers): Fix prototype construction

src/providers/caniuse-provider.ts, test/e2e.spec.ts
updated can i use provider for requestIdleCallback and requestAnimationFrame
Fixes
https://github.com/amilajack/eslint-plugin-compat/issues/554 - requestIdleCallback 
https://github.com/amilajack/eslint-plugin-compat/issues/302 - requestAnimationFrame issue mentioned in discussion
=> fix: requestIdleCallback and requestAnimationFrame provider

package-lock.json, package.json
```
semver  7.0.0 - 7.5.1
Severity: moderate
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
```
```
├─┬ eslint-plugin-compat@4.1.4
│ └── semver@7.3.8
```
I don't know why you don't use `^`, so I left it the same. By the way, if not for this, the PR would not be needed.
I propose as an alternative https://github.com/amilajack/eslint-plugin-compat/pull/583 . I think it's more likely that the problem will be solved.
=> update semver (audit problem)

src/helpers.ts, src/rules/compat.ts, src/types.ts
In your ESLint config, you can now add `settings.browserslistOpts` to configure which settings to pass to the [Browserslist JS API](https://github.com/browserslist/browserslist#js-api). 
For example, this would change the environment that Browserslist uses from `production` (the default) to `otherEnv`:
```json
{
"settings": {
"browserslistOpts": {
"env": "otherEnv"
}
}
}
```
Closes #392 by allowing each ESLint config in a project to specify its own Browserslist env to choose from. 
(I tested this in a personal repo and it works great!)
=> feat: Enable setting Browserslist JS API options

.github/workflows/codeql-analysis.yml, .github/workflows/release.yml, .github/workflows/test.yml
If you are using advanced CodeQL configurations, please refer to this post: https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/#how-does-this-affect-me
=> chore: bump workflows

.prettierignore, README.md, docs/rules/compat.md, eslint.config.mjs, package-lock.json, package.json, src/helpers.ts, src/providers/mdn-provider.ts, src/rules/compat.ts, src/types.ts, test/__snapshots__/helpers.spec.ts.snap, test/benchmarks.ts, test/e2e.spec.ts, test/multi-config.package.json, test/repos.ts, test/single-version-config.package.json
Adds ESLint 9 support.
Attempts to dogfood with flat config and ESLint 9 use internally, but a few plugins could not be upgraded (See the config file).
I also upgraded a number of dependencies/devDeps and adjusted tests accordingly.
This still should need a closer look and testing (I couldn't get the spec:e2e script working though that could be a slow connection where I am), but I thought I'd try to get the ball rolling with this draft.
=> feat: eslint 9 support

src/index.ts
ESLint [recommends](https://eslint.org/docs/latest/use/configure/configuration-files#configuration-naming-conventions) a name for flat configs.
Tools like https://github.com/eslint/config-inspector can use this to indicate the source of rules.
This PR adds that `name` to the current (flat) config. (It is not possible to add a name to the legacy config as it will err there.)
=> feat: add `name` (for tooling)

package-lock.json, package.json, src/providers/mdn-provider.ts, test/__snapshots__/helpers.spec.ts.snap
eslint-plugin-compat has fallen far behind `@mdn/browser-compat-data` which means it's missing a lot of browser APIs that have been added and isn't useable for most purposes.
This PR updates it to the latest version of MDN and accommodates a breaking change between BCD 5.x.x and 6.x.x.  It also updates the Jest snapshot to ensure tests pass.
Let me know if you have any questions.
=> Updates @mdn/browser-compat-data, browserslist, updates Jest snapshot
