amilajack/eslint-plugin-compat

package.json

Closes https://github.com/amilajack/eslint-plugin-compat/issues/87

Allow peerDependency of eslint@4.0.0

---

.travis.yml
src/providers/CanIUseProvider.js
test/e2e.spec.js

Closes https://github.com/amilajack/eslint-plugin-compat/issues/97

Added Promise support

---

src/providers/CanIUseProvider.js
test/e2e.spec.js

Add API support for URL and URLSearchParams

---

README.md
src/config/recommended.js
src/index.js

Fix and improve recommended config

---

src/providers/CanIUseProvider.js
test/e2e.spec.js

resolve https://github.com/amilajack/eslint-plugin-compat/issues/114
@amilajack or anyone else
would you take a look at it? 🙏

Add support for High Resolution Timing API

---

src/providers/CanIUseProvider.js

Here is a nits refactor.
Separating `CanIUseProvider#getUnsupportedTargets()` because it looks a little bit complicated.
This method has there 2 logics, so split into different methods as follows:
- `canIUseSupported()` ... check if canIUse supported
- `getUnsupportedTargets()` (original) ... get stats & map browser identifiers
please revieiw 🙏

Refactor CanIUseProvider#getUnsupportedTargets()

---

.travis.yml
CHANGELOG.md
README.md
src/providers/CanIUseProvider.js
test/e2e.spec.js

Fixes https://github.com/amilajack/eslint-plugin-compat/issues/122

add caniuse Object.values support

---

README.md

Closes https://github.com/amilajack/eslint-plugin-compat/issues/149

add docs for default browserslist config

---

src/providers/CanIUseProvider.js
test/e2e.spec.js

Closes https://github.com/amilajack/eslint-plugin-compat/issues/201

add support for typed arrays

---

docs/rules/compat.md
src/rules/compat.js

add link to rule documentation

---

CHANGELOG.md

Add changelog entry for #246

---

src/providers/CanIUseProvider.js

https://caniuse.com/#feat=resizeobserver

Add ResizeObserver rule

---

CHANGELOG.md
src/providers/CanIUseProvider.js
test/e2e.spec.js

Fixes https://github.com/amilajack/eslint-plugin-compat/issues/264

allow targets not caniuse db

---

package.json
src/Lint.js
src/LintTypes.js
src/Versioning.js
src/config/recommended.js
src/index.js
src/providers/CanIUseProvider.js
src/providers/KangaxProvider.js
src/providers/MdnProvider.js
src/providers/index.js
src/rules/compat.js
test/CanIUseProvider.spec.js
test/MdnProvider.spec.js
test/Versioning.spec.js
test/__snapshots__/Versioning.spec.js.snap
test/e2e.spec.js
yarn.lock

Fixes https://github.com/amilajack/eslint-plugin-compat/issues/321
Fixes #297 
Fixes #321 
Fixes #292 
Fixes #320 
Fixes https://github.com/amilajack/eslint-plugin-compat/issues/322
Fixes https://github.com/amilajack/eslint-plugin-compat/issues/239
Fixes https://github.com/amilajack/eslint-plugin-compat/issues/229
Fixes https://github.com/amilajack/eslint-plugin-compat/issues/231

bump ast-metadata-inferer

---

src/Versioning.js

Support defining target browsers in both `.eslintrc` and `browserslist`. Previously, configs were assumed to exist in a mutually exclusive manner.

feat: merge targets defined in eslint and browserslist configs

---

azure-pipelines.yml

Right now LTS is 12.x and current is 14.x

Bump node version in CI pipeline

---

CHANGELOG.md

update changelog for #348

---

azure-pipelines.yml

- Add display names for clarity in CI steps
- Fix some docs in .yml

Display names in ci

---

test/benchmarks.ts

- Add repos and closes #352 
- Some bug fixes
- Lowered max benchmark time to 10s

Add benchmark repos

---

azure-pipelines.yml
package.json

- Fix eslint versioning check for `spec:e2e` 
- Remove unused comments

Azure yml fix

---

.github/workflows/release.yml
package.json
yarn.lock

- Add missing deps needed for semantic release
- Fix `release.yml` syntax

ci: semantic release fix

---

package.json
yarn.lock

chore(deps): replace mdn-browser-compat-data with @mdn/browser-compat-data

---

.eslintrc.js
package.json
src/helpers.ts
src/rules/compat.ts
test/__snapshots__/helpers.spec.ts.snap
test/benchmarks.ts
test/e2e.spec.ts
yarn.lock

Closes https://github.com/amilajack/eslint-plugin-compat/issues/477

chore: bump deps

---

README.md

docs: add `plugins` prop to eslint config section

---

README.md
src/rules/compat.ts

closes https://github.com/amilajack/eslint-plugin-compat/issues/507

fix: remove tsconfig from polyfill check
